### ISSUE TITLE
Calcolo consumo energetico

### ISSUE THREAD

**Issue by orginda** [daxda/HomeAssistant#1]
ciao, complimenti per come hai ben sistemato il tuo home assistant, veramente lodevole, ho provato a creare il mio resoconto di carico consumi, ho visto che tu alla pagina dei consumi hai messo un grafico che ti ricrea "consumo energetico" con delle bande che ti fa vedere ad ogni ora il relativo consumo, come l'hai creato? Io provandoci riesco ad ottenere sempre un totale cioè il rapporto consumo fascia oraria nel corso della giornata si sommano, con il risultato che l'ora corrente è sempre la somma di tutte le ore precedenti, mi sfugge qualcosa mi sa

**Comment by daxda** [comment]
ciao , è il componente custom      mini-graph-card , lo installi tramite  hacs

 ```
  - type: custom:mini-graph-card
          entities:
            - entity: sensor.consumi_generali_filtered
          name: Consumo Energetico
          show:
            graph: bar
```
